import type { Post, Book, BookReview, Poll, Event, ChatThread, ChatMessage, Contest, Birthday } from "./types";

export const mockPosts: Post[] = [
  {
    id: "1",
    authorId: "admin1",
    authorName: "Лена",
    authorAvatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Lena",
    content: "Добро пожаловать в наш уютный книжный клуб! В этом месяце мы читаем «Щегол» Донны Тартт — невероятный роман о потере, искусстве и поиске себя. Присоединяйтесь к обсуждению!",
    imageUrl: "https://images.unsplash.com/photo-1524578271613-d550eacf6090?w=600&h=400&fit=crop",
    createdAt: "2026-07-01T10:00:00Z",
  },
  {
    id: "2",
    authorId: "admin1",
    authorName: "Лена",
    authorAvatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Lena",
    content: "Напоминаю, что 12 июля в 19:00 — наша ежемесячная онлайн-встреча. Обсудим впечатления от «Щегла». Готовьте свои любимые цитаты!",
    createdAt: "2026-07-03T14:30:00Z",
  },
  {
    id: "3",
    authorId: "admin2",
    authorName: "Даша",
    authorAvatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Dasha",
    content: "Девочки, открыто голосование за книгу на август! Три потрясающих кандидата — заходите в раздел голосований и выбирайте.",
    imageUrl: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&h=400&fit=crop",
    createdAt: "2026-07-02T09:15:00Z",
  },
];

export const mockBooks: Book[] = [
  {
    id: "1",
    title: "Щегол",
    author: "Донна Тартт",
    coverUrl: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=300&h=450&fit=crop",
    description: "Тринадцатилетний Тео Декер чудом остаётся жив после взрыва в музее, унёсшего жизнь его матери. Эта трагедия меняет всю его жизнь — он оказывается в мире искусства, антикварной мебели и преступного подполья.",
    month: 7,
    year: 2026,
    isCurrent: true,
    rating: 4.5,
    reviewCount: 12,
  },
  {
    id: "2",
    title: "Маленькая жизнь",
    author: "Ханья Янагихара",
    coverUrl: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=300&h=450&fit=crop",
    description: "История четырёх друзей, переехавших в Нью-Йорк после колледжа. Роман о дружбе, травме и силе человеческого духа.",
    month: 6,
    year: 2026,
    isCurrent: false,
    rating: 4.8,
    reviewCount: 18,
  },
  {
    id: "3",
    title: "Норвежский лес",
    author: "Харуки Мураками",
    coverUrl: "https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=300&h=450&fit=crop",
    description: "Ностальгическая история любви, потери и взросления в Токио конца 1960-х.",
    month: 5,
    year: 2026,
    isCurrent: false,
    rating: 4.3,
    reviewCount: 15,
  },
  {
    id: "4",
    title: "Гордость и предубеждение",
    author: "Джейн Остин",
    coverUrl: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=300&h=450&fit=crop",
    description: "Вечная история о том, как первое впечатление обманчиво, а настоящая любовь побеждает гордость и предрассудки.",
    month: 4,
    year: 2026,
    isCurrent: false,
    rating: 4.7,
    reviewCount: 20,
  },
  {
    id: "5",
    title: "1984",
    author: "Джордж Оруэлл",
    coverUrl: "https://images.unsplash.com/photo-1524578271613-d550eacf6090?w=300&h=450&fit=crop",
    description: "Антиутопия о тоталитарном обществе, где Большой Брат следит за каждым.",
    month: 3,
    year: 2026,
    isCurrent: false,
    rating: 4.6,
    reviewCount: 22,
  },
  {
    id: "6",
    title: "Три товарища",
    author: "Эрих Мария Ремарк",
    coverUrl: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=300&h=450&fit=crop",
    description: "Трогательная история дружбы и любви на фоне Германии времён Веймарской республики.",
    month: 2,
    year: 2026,
    isCurrent: false,
    rating: 4.9,
    reviewCount: 24,
  },
];

export const mockBookReviews: BookReview[] = [
  {
    id: "1",
    bookId: "1",
    userId: "user1",
    userName: "Аня",
    userAvatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Anya",
    rating: 5,
    text: "Невероятная книга! Тартт мастерски создаёт атмосферу и держит в напряжении до последней страницы. Обязательно к прочтению.",
    createdAt: "2026-07-05T12:00:00Z",
  },
  {
    id: "2",
    bookId: "1",
    userId: "user2",
    userName: "Катя",
    userAvatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Katya",
    rating: 4,
    text: "Красивый язык, глубокие персонажи. Немного затянуто в середине, но финал всё искупает.",
    createdAt: "2026-07-04T18:00:00Z",
  },
  {
    id: "3",
    bookId: "1",
    userId: "user3",
    userName: "Маша",
    userAvatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Masha",
    rating: 5,
    text: "Одна из лучших книг, что я читала за последние годы. Тео — такой живой и настоящий персонаж.",
    createdAt: "2026-07-03T09:30:00Z",
  },
];

export const mockPolls: Poll[] = [
  {
    id: "1",
    title: "Книга на август",
    type: "book",
    deadline: "2026-07-25T23:59:59Z",
    isActive: true,
    totalMembers: 24,
    votedCount: 18,
    options: [
      { id: "1a", title: "Тысяча сияющих солнц", description: "Халед Хоссейни", imageUrl: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=200&h=300&fit=crop", votes: 8 },
      { id: "1b", title: "Исчезнувшая", description: "Гиллиан Флинн", imageUrl: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=200&h=300&fit=crop", votes: 6 },
      { id: "1c", title: "Девушка в поезде", description: "Пола Хокинс", imageUrl: "https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=200&h=300&fit=crop", votes: 4 },
    ],
  },
  {
    id: "2",
    title: "Дата встречи в июле",
    type: "date",
    deadline: "2026-07-08T23:59:59Z",
    isActive: true,
    totalMembers: 24,
    votedCount: 20,
    options: [
      { id: "2a", title: "12 июля, суббота", votes: 11 },
      { id: "2b", title: "13 июля, воскресенье", votes: 5 },
      { id: "2c", title: "19 июля, суббота", votes: 4 },
    ],
  },
  {
    id: "3",
    title: "Книга на июль",
    type: "book",
    deadline: "2026-06-25T23:59:59Z",
    isActive: false,
    totalMembers: 24,
    votedCount: 22,
    options: [
      { id: "3a", title: "Щегол", description: "Донна Тартт", votes: 12 },
      { id: "3b", title: "Бегущий за ветром", description: "Халед Хоссейни", votes: 7 },
      { id: "3c", title: "Книжный вор", description: "Маркус Зусак", votes: 3 },
    ],
  },
];

export const mockEvents: Event[] = [
  {
    id: "1",
    title: "Встреча с автором Гузель Яхиной",
    description: "Квартальное мероприятие с приглашённым гостем. Гузель Яхина расскажет о своём творческом пути и ответит на вопросы участниц клуба.",
    date: "2026-07-26T18:00:00Z",
    location: "Zoom",
    type: "quarterly",
    speakerName: "Гузель Яхина",
    speakerInfo: "Автор романов «Зулейха открывает глаза» и «Дети мои»",
    isOnline: true,
    rsvpGoing: 14,
    rsvpTotal: 24,
    isPast: false,
    hasPhotos: false,
  },
  {
    id: "2",
    title: "Обсуждение «Щегол»",
    description: "Ежемесячная онлайн-встреча по книге месяца. Обсудим впечатления, любимые моменты и персонажей.",
    date: "2026-07-12T19:00:00Z",
    location: "Google Meet",
    type: "monthly",
    isOnline: true,
    rsvpGoing: 18,
    rsvpTotal: 24,
    isPast: false,
    hasPhotos: false,
  },
  {
    id: "3",
    title: "Обсуждение «Маленькая жизнь»",
    description: "Эмоциональное обсуждение одного из самых сильных романов последних лет.",
    date: "2026-06-14T19:00:00Z",
    location: "Google Meet",
    type: "monthly",
    isOnline: true,
    rsvpGoing: 20,
    rsvpTotal: 24,
    isPast: true,
    hasPhotos: true,
  },
  {
    id: "4",
    title: "Обсуждение «Норвежский лес»",
    description: "Разбор атмосферного романа Мураками.",
    date: "2026-05-18T19:00:00Z",
    location: "Google Meet",
    type: "monthly",
    isOnline: true,
    rsvpGoing: 16,
    rsvpTotal: 24,
    isPast: true,
    hasPhotos: true,
  },
];

export const mockThreads: ChatThread[] = [
  {
    id: "general",
    title: "Общий чат",
    isPinned: true,
    lastMessage: "Девочки, кто уже дочитал? Я в восторге от финала!",
    lastMessageAuthor: "Аня",
    lastMessageTime: "2 мин",
    unreadCount: 3,
    icon: "📌",
  },
  {
    id: "book-1",
    title: "Обсуждение: Щегол",
    bookId: "1",
    isPinned: false,
    lastMessage: "Глава 15 просто невероятная, как он описывает...",
    lastMessageAuthor: "Мария",
    lastMessageTime: "1 ч",
    unreadCount: 7,
    icon: "📖",
  },
  {
    id: "book-2",
    title: "Обсуждение: Маленькая жизнь",
    bookId: "2",
    isPinned: false,
    lastMessage: "Это самая грустная книга что я когда-либо читала",
    lastMessageAuthor: "Катя",
    lastMessageTime: "вчера",
    unreadCount: 0,
    icon: "📖",
  },
  {
    id: "recommendations",
    title: "Рекомендации",
    isPinned: false,
    lastMessage: "Советую всем «Тысяча сияющих солнц» — шедевр!",
    lastMessageAuthor: "Лена",
    lastMessageTime: "2 дня",
    unreadCount: 0,
    icon: "💡",
  },
  {
    id: "offtop",
    title: "Оффтоп",
    isPinned: false,
    lastMessage: "Кто идёт на книжную выставку в субботу?",
    lastMessageAuthor: "Даша",
    lastMessageTime: "3 дня",
    unreadCount: 0,
    icon: "☕",
  },
];

export const mockMessages: ChatMessage[] = [
  {
    id: "m1",
    threadId: "general",
    userId: "user1",
    userName: "Аня",
    userAvatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Anya",
    content: "Девочки, кто уже дочитал? Я в восторге от финала!",
    createdAt: "2026-07-05T10:30:00Z",
    isOwn: false,
  },
  {
    id: "m2",
    threadId: "general",
    userId: "user2",
    userName: "Катя",
    userAvatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Katya",
    content: "Я на середине пока, не спойлерите! 😄",
    createdAt: "2026-07-05T10:31:00Z",
    isOwn: false,
  },
  {
    id: "m3",
    threadId: "general",
    userId: "me",
    userName: "Вы",
    userAvatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Me",
    content: "Я почти дочитала, последние 50 страниц остались!",
    createdAt: "2026-07-05T10:32:00Z",
    isOwn: true,
  },
  {
    id: "m4",
    threadId: "general",
    userId: "user3",
    userName: "Маша",
    userAvatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Masha",
    content: "Готовьтесь к встрече 12-го, будет что обсудить! 📚",
    createdAt: "2026-07-05T10:33:00Z",
    isOwn: false,
  },
  {
    id: "m5",
    threadId: "general",
    userId: "user1",
    userName: "Аня",
    userAvatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Anya",
    content: "Обожаю наш клуб! 💕 Кстати, не забудьте проголосовать за книгу на август",
    createdAt: "2026-07-05T10:35:00Z",
    isOwn: false,
  },
];

export const mockContests: Contest[] = [
  {
    id: "1",
    title: "Викторина по «Щегол»",
    description: "Ответьте на 10 вопросов по книге месяца и выиграйте подарок! Проверьте, насколько внимательно вы читали.",
    prize: "Книга с автографом автора",
    deadline: "2026-07-20T23:59:59Z",
    isActive: true,
    participantCount: 12,
  },
  {
    id: "2",
    title: "Лучший отзыв мая",
    description: "Напишите самый интересный и глубокий отзыв на «Норвежский лес» Мураками.",
    prize: "Подарочный сертификат в книжный магазин",
    deadline: "2026-05-31T23:59:59Z",
    isActive: false,
    participantCount: 8,
    winnerName: "Мария Иванова",
  },
  {
    id: "3",
    title: "Угадай книгу по цитате",
    description: "Серия цитат из классических произведений — угадайте все и получите приз!",
    prize: "Набор закладок ручной работы",
    deadline: "2026-04-15T23:59:59Z",
    isActive: false,
    participantCount: 15,
    winnerName: "Анна Петрова",
  },
];

export const mockBirthdays: Birthday[] = [
  {
    userId: "user1",
    userName: "Анна Петрова",
    userAvatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Anya",
    date: "2026-07-15",
  },
  {
    userId: "user3",
    userName: "Мария Сидорова",
    userAvatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Masha",
    date: "2026-07-22",
  },
];
